version: '3'
services:
  myapp-main:
    image: sdat-qap:latest
    ports:
      - "8080:8080"
    environment:
      #- spring.datasource.url=jdbc:mysql://host.docker.internal:3306/spring_2022
      - spring.datasource.url=jdbc:mysql://database-sdat2.cuggm45mmbek.us-east-1.rds.amazonaws.com/rileys_db
      - spring.datasource.password=password
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver